//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedleyPharmaceuticals
{
    public partial class ReceivedGood
    {
        public int Id { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public string GRNNo { get; set; }
        public string MaterialName { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime MfgDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string QuantityReceived { get; set; }
        public int NoOfCartons { get; set; }
        public string Supplier { get; set; }
        public string ReferenceNo { get; set; }
        public bool DeliveredToStore { get; set; }
        public int StockId { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
