//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace MedleyPharmaceuticals
{
    public partial class Stock
    {
        public Stock()
        {
            this.ReceivedGoods = new ObservableListSource<ReceivedGood>();
        }
    
        public int Id { get; set; }
        public string NoOfCartons { get; set; }
    
        public virtual ObservableListSource<ReceivedGood> ReceivedGoods { get; set; }
    }
}
